### ISSUE TITLE
Question: Ubuntu 24.04 Version

### ISSUE THREAD

**Issue by guenhter** [mitogen-hq/mitogen#1156]
Hi,

this is more of a question, because I'm also not too familiar with the Ubuntu package management system.
Is there anything you can do, that the package manager of Ubuntu 24.04 get a more recent version of the `python3-mitogen` package, or is this completely outside of the scope?

**Comment by moreati** [comment]
Short answer: No

Medium answer:
Ubuntu packaging is done by the Ubuntu maintainers, they also decide what to include. To make a release like 24.04 they take a snapshot of package versions a few months before, then they freeze those versions for the lifetime of that Ubuntu release. The exceptions are mostly security updates.

I won't go into PPAs here, because there aren't any for Mitogen.

**Comment by guenhter** [comment]
Thx

**Comment by moreati** [comment]
thank you. you inspired me to think more about the broader installation situation. So far: #1158 and #1158
